stages:
  - containerize
  - deploy

include:
  - project: "cicd/gitlab-ci-templates"
    file: "containerize/docker-ucrb-yarn.yml"
  - project: "cicd/gitlab-ci-templates"
    file: "deploy/deploy-universal.yml"
